name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Download microservices
        run: wget https://github.com/mpchadwick/hello-server/releases/download/v0.1.1/hello-server_0.1.1_Linux_x86_64.tar.gz
      - name: Unzip microservice
        run: tar xzf hello-server_0.1.1_Linux_x86_64.tar.gz
      - name: Start microservice
        run: ./hello-server &
      - uses: helaili/jekyll-action@2.0.1
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}